"""update task model

Revision ID: 367aa3c0caf7
Revises: c372e9aab95f
Create Date: 2026-10-05 16:02:51.314434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '367aa3c0caf7'
down_revision: Union[str, Sequence[str], None] = 'c372e9aab95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('tasks', 'destination_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'destination_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('tasks', 'updated_at')
    # ### end Alembic commands ###
