from datetime import datetime
from app.database import SessionLocal
from app.models import Task

def seed_tasks():
    db=SessionLocal()
    try:
        if db.query(Task).count() > 0:
            return
        tasks=[
            {'title': '🎬 YouTube Video View #1', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/h2sWOP9yyDI?si=zwxCifWSsoF2EOi5', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #2', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/5z66Oxy90-o?si=yFC1Ho9G0KB9I2c3', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #3', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/BmY6kjCChXY?si=DcYVltEOt2TzRlXp', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #4', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/GTogzcAtJFY?si=UpyNw9HR4lOY43z8', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #5', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/1_19F0vgnIE?si=e4Cgh2fEI0aPtI8R', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #6', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/Tqc0RrmaCug?si=hLcU7RkTKvjs1I9b', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #7', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/NUq_ekIpIlI?si=sqSCS4uAkHexnWSN', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #8', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/1gXquoPaL-0?si=gawyCtleoYQoz1WT', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #9', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/u7NRrbbvxK0?si=103Fulw8RQhD_2kY', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #10', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/WcihoyXI11w?si=9KYrSPysksFQAj7G', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #11', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/gFA_hm1KOOw?si=13OEd-W94Uz2kHDI', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #12', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/1lHuavMx0Sw?si=J0u8es_2c1np0RUp', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #13', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/GHp6b4RXX_4?si=2jsm2q_Guy_vsgHs', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #14', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/lSq3ODETbwc?si=27w1woA7e00AIo-N', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🎬 YouTube Video View #15', 'description': '🎥 ভিডিওটি সম্পূর্ণ দেখুন', 'task_type': 'youtube_video', 'destination_url': 'https://youtube.com/shorts/XhxoqhG_4EQ?si=TWGEmuBvOF_Vm0Ex', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🔔 YouTube Channel Subscribe #1', 'description': '📺 চ্যানেলটি Subscribe করুন', 'task_type': 'youtube_subscribe', 'destination_url': 'https://youtube.com/@toxic2.0-u2p?si=Urto1yoNqKK0cp_c', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🔔 YouTube Channel Subscribe #2', 'description': '📺 চ্যানেলটি Subscribe করুন', 'task_type': 'youtube_subscribe', 'destination_url': 'https://youtube.com/@itsmeruku42?si=Iovr5Ehn2qw3bhJ_', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🔔 YouTube Channel Subscribe #3', 'description': '📺 চ্যানেলটি Subscribe করুন', 'task_type': 'youtube_subscribe', 'destination_url': 'https://www.youtube.com/@JannatMuni-ub8gs', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🔔 YouTube Channel Subscribe #4', 'description': '📺 চ্যানেলটি Subscribe করুন', 'task_type': 'youtube_subscribe', 'destination_url': 'https://youtube.com/@toxic-yc2ut?si=ZTJ6NCU_jic8HmO8', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '🔔 YouTube Channel Subscribe #5', 'description': '📺 চ্যানেলটি Subscribe করুন', 'task_type': 'youtube_subscribe', 'destination_url': 'https://youtube.com/@kitchin24?si=CiyJpZr41O8j-5BG', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #1', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11950217', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #2', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11942844', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #3', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11942845', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #4', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11950214', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #5', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11950215', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #6', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11950217', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #7', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11942844', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #8', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11942845', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #9', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11950214', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #10', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11950215', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #11', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11950217', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #12', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11942844', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #13', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11942845', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #14', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11950214', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
            {'title': '💰 Monetag Smart Link #15', 'description': '🔗 Smart Link খুলে নির্ধারিত কাজ সম্পন্ন করুন', 'task_type': 'monetag_smartlink', 'destination_url': 'https://omg10.com/4/11950215', 'reward_amount': 0.5, 'daily_limit': 1, 'cooldown_seconds': 0, 'verification_type': 'manual', 'status': 'active'},
        ]
        for item in tasks:
            db.add(Task(**item))
        db.commit()
    finally:
        db.close()

if __name__ == "__main__":
    seed_tasks()